# Generated by Django 5.0.6 on 2024-07-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_message_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='subjects',
            new_name='subject',
        ),
    ]
